create table if not exists public.menu (
    id text primary key,
    name text not null,
    price numeric not null check (price >= 0),
    category text not null,
    image_url text,
    description text default '',
    created_at timestamptz not null default now()
);

create table if not exists public.discounts (
    code text primary key,
    discount_percent integer not null check (discount_percent > 0 and discount_percent <= 100),
    active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.customers (
    id bigint generated by default as identity primary key,
    name text not null,
    phone text not null,
    table_num text not null,
    unique (name, phone, table_num)
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    customer_id bigint not null references public.customers(id),
    items jsonb not null,
    total_price numeric not null check (total_price >= 0),
    status text not null default 'Chờ pha chế',
    created_at timestamptz not null default now()
);

alter table public.menu enable row level security;
alter table public.discounts enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;

drop policy if exists "app menu access" on public.menu;
create policy "app menu access" on public.menu for all to anon, authenticated using (true) with check (true);
drop policy if exists "app discounts access" on public.discounts;
create policy "app discounts access" on public.discounts for all to anon, authenticated using (true) with check (true);
drop policy if exists "app customers access" on public.customers;
create policy "app customers access" on public.customers for all to anon, authenticated using (true) with check (true);
drop policy if exists "app orders access" on public.orders;
create policy "app orders access" on public.orders for all to anon, authenticated using (true) with check (true);